title: "VC Database"
description: "A database of 1500+ VC firms."
baseurl: "" # Use "" for root deployment
url: "https://pkprojectstartups.github.io/vclist.online" # Replace with your username
theme: minima
plugins:
  - jekyll-paginate
paginate: 20 # Number of firms per page

collections:
  vc_firms:
    output: true # This will ensure Jekyll generates individual pages
