# Basic Site Settings
title: "VC Database"
description: "A database of 1500+ VC firms."
baseurl: "/vclist.online"  # Path after your GitHub Pages URL
url: "https://pkprojectstartups.github.io"  # Replace with your GitHub username or organization

# Theme Settings
theme: minima

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 20

# Collections
collections:
  vc_firms:
    output: true  # Ensures individual VC firm pages are generated
    permalink: /:title/  # Pretty URLs based on firm title
  custom_lists:
    output: true  # Ensures custom list pages are generated


exclude:
  - search.json


# Markdown Configuration
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown

# Permalinks
permalink: pretty  # Clean URLs
