# Basic Site Settings
title: "Project Startups – Open Access VC & Funded Startups Database"
description: "Project Startups offers an open-access VC firms database, funded startup directory, and curated tools to support entrepreneurs, investors, and researchers."
baseurl: ""  # Path after your GitHub Pages URL
url: "https://vc.projectstartups.com"  # Local server URL"  # Replace with your GitHub username or organization

# Theme Settings
theme: minima

styles:
  - assets/css/style.css


# Collections
collections:
  vc_firms:
    output: true  # Ensures individual VC firm pages are generated
    permalink: /:title/  # Pretty URLs based on firm title
  custom_lists:
    output: true  # Ensures custom list pages are generated


# Markdown Configuration
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown

# Permalinks
permalink: pretty  # Clean URLs

include:
  - search.json
plugins:
- jekyll-sitemap
